# cleanup-local.ps1
#
# Safe local cleanup for the Next.js -> TanStack Start migration.
#
# DESIGN RULE: this script never deletes a file it hasn't first PROVEN is
# unreferenced. Each candidate is grepped across src/ and scripts/ and skipped
# (loudly) if anything still imports it. Run it as many times as you like.
#
#   cd D:\Projects\lifemarkai\migration\tanstack-start-app
#   .\cleanup-local.ps1            # report only, deletes nothing
#   .\cleanup-local.ps1 -Apply     # actually delete
#
# After -Apply, re-run `npm run build`. A green build is the real proof.

param([switch]$Apply)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
Set-Location $root

function Test-Referenced {
    param([string]$RelPath)
    # Match how it would be imported: by module specifier, not by full path.
    $leaf   = [IO.Path]::GetFileNameWithoutExtension($RelPath)
    $parent = Split-Path (Split-Path $RelPath -Parent) -Leaf
    $needles = @($leaf)
    if ($parent -and $parent -ne "lib" -and $parent -ne "scripts" -and $parent -ne "src") {
        $needles += "$parent/$leaf"
    }

    $hits = @()
    foreach ($n in $needles) {
        $found = Get-ChildItem -Path src,scripts -Recurse -File `
                    -Include *.ts,*.tsx,*.mjs,*.js -ErrorAction SilentlyContinue |
                 Where-Object { $_.FullName -ne (Join-Path $root $RelPath) } |
                 Select-String -Pattern ([regex]::Escape($n)) -SimpleMatch -List -ErrorAction SilentlyContinue
        if ($found) { $hits += $found }
    }
    return $hits
}

# ── 1. Retired migration stubs + dead compat shims ──────────────────────────
# All of these were emptied to `// PHASE ...` markers, or superseded:
#   next-dynamic.tsx      -> renamed to lazy-component.tsx (all 6 importers moved)
#   next-shims/server-only-> Next-only construct, nothing imports it under Vite
$candidates = @(
    "src\lib\next-dynamic.tsx",
    "src\lib\next-shims\server-only.ts",
    "src\lib\api-adapter.ts",
    "src\lib\api-worker-client.ts",
    "src\lib\dispatch-or-native.ts",
    "src\lib\worker-proxy.ts",
    "src\lib\sandbox-http.ts",
    "src\lib\sandbox-worker-client.ts",
    "src\lib\server-fns\ai-json.ts",
    "src\lib\server-fns\proxy-json.ts",
    "scripts\api-http-worker.mjs",
    "scripts\build-api-manifest.mjs",
    "scripts\verify-api-coverage.mjs"
)

Write-Host "`n=== Dead-file sweep ===" -ForegroundColor Cyan
$toDelete = @()
$blocked  = @()

foreach ($c in $candidates) {
    if (-not (Test-Path $c)) { continue }
    $refs = Test-Referenced $c
    if ($refs) {
        $blocked += $c
        Write-Host ("  SKIP  {0}" -f $c) -ForegroundColor Yellow
        $refs | Select-Object -First 3 | ForEach-Object {
            Write-Host ("          still referenced by {0}" -f $_.Path) -ForegroundColor DarkYellow
        }
    } else {
        $toDelete += $c
        $size = (Get-Item $c).Length
        Write-Host ("  DEAD  {0}  ({1} bytes)" -f $c, $size) -ForegroundColor Green
    }
}

# ── 2. Stale AI-worker bundles ──────────────────────────────────────────────
# .tmp/ai-http is a build cache. `prebuild` regenerates it on every
# `npm run build`, so deleting it only forces a clean rebuild.
$tmpAi = ".tmp\ai-http"
$hasTmp = Test-Path $tmpAi

Write-Host "`n=== Build caches ===" -ForegroundColor Cyan
if ($hasTmp) { Write-Host "  STALE .tmp\ai-http (regenerated by prebuild)" -ForegroundColor Green }
else         { Write-Host "  .tmp\ai-http absent — nothing to clear" }

# ── 3. Act ──────────────────────────────────────────────────────────────────
if (-not $Apply) {
    Write-Host "`nDRY RUN — nothing deleted." -ForegroundColor Cyan
    Write-Host ("  would delete : {0} file(s)" -f $toDelete.Count)
    Write-Host ("  blocked      : {0} file(s) still referenced" -f $blocked.Count)
    Write-Host "`nRe-run with -Apply to delete:  .\cleanup-local.ps1 -Apply"
    exit 0
}

foreach ($f in $toDelete) { Remove-Item $f -Force; Write-Host "  removed $f" }
if ($hasTmp) { Remove-Item $tmpAi -Recurse -Force; Write-Host "  cleared $tmpAi" }

# Drop src\lib\next-shims entirely if it ended up empty.
if ((Test-Path "src\lib\next-shims") -and -not (Get-ChildItem "src\lib\next-shims" -Force)) {
    Remove-Item "src\lib\next-shims" -Force
    Write-Host "  removed empty dir src\lib\next-shims"
}

Write-Host "`nDone. Deleted $($toDelete.Count) file(s)." -ForegroundColor Green
if ($blocked.Count -gt 0) {
    Write-Host "$($blocked.Count) file(s) were kept because something still imports them." -ForegroundColor Yellow
}
Write-Host "`nNOW VERIFY:  npm run build" -ForegroundColor Cyan
Write-Host "A green build is the only real proof nothing here was load-bearing."
