"use client";

import { useState, useEffect, useCallback } from "react";
import { Palette, Type, Sliders, Download, Sparkles, Check, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import type { ProjectFile } from "@/types/database";

interface DesignSystemPanelProps {
  projectId: string;
  files: ProjectFile[];
  onFilesUpdate: (files: ProjectFile[]) => void;
}

interface ColorToken {
  key: string;
  label: string;
  value: string;
  description: string;
}

interface TypographyToken {
  fontSans: string;
  fontMono: string;
  baseSizePx: number;
}

interface RadiusToken {
  base: number; // px
}

const DEFAULT_COLORS: ColorToken[] = [
  { key: "primary",     label: "Primary",     value: "#7c3aed", description: "Main brand color for buttons & links" },
  { key: "secondary",   label: "Secondary",   value: "#6b7280", description: "Supporting UI elements" },
  { key: "accent",      label: "Accent",      value: "#f59e0b", description: "Highlights and CTAs" },
  { key: "destructive", label: "Destructive",  value: "#ef4444", description: "Errors and danger actions" },
  { key: "background",  label: "Background",  value: "#ffffff", description: "Page background" },
  { key: "foreground",  label: "Foreground",  value: "#09090b", description: "Primary text" },
  { key: "muted",       label: "Muted",       value: "#f4f4f5", description: "Subdued surfaces" },
  { key: "border",      label: "Border",      value: "#e4e4e7", description: "Dividers and outlines" },
];

const FONT_OPTIONS = [
  "Inter", "Geist", "Roboto", "DM Sans", "Poppins", "Nunito", "Outfit",
  "Plus Jakarta Sans", "Manrope", "Lato", "Open Sans", "Source Sans 3",
];

const MONO_OPTIONS = [
  "Geist Mono", "JetBrains Mono", "Fira Code", "Source Code Pro",
  "IBM Plex Mono", "Cascadia Code", "Roboto Mono",
];

function hexToHsl(hex: string): { h: number; s: number; l: number } {
  let r = 0, g = 0, b = 0;
  if (hex.length === 7) {
    r = parseInt(hex.slice(1, 3), 16) / 255;
    g = parseInt(hex.slice(3, 5), 16) / 255;
    b = parseInt(hex.slice(5, 7), 16) / 255;
  }
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }
  return { h: Math.round(h * 360), s: Math.round(s * 100), l: Math.round(l * 100) };
}

function generateCSSFile(
  colors: ColorToken[],
  typography: TypographyToken,
  radius: RadiusToken
): string {
  const hslVars = colors
    .map((c) => {
      const { h, s, l } = hexToHsl(c.value);
      return `  --${c.key}: ${h} ${s}% ${l}%;`;
    })
    .join("\n");

  return `/* ================================================
   Design System — generated by LifemarkAI
   Edit tokens in the Design Systems panel
   ================================================ */

@layer base {
  :root {
${hslVars}

    /* Typography */
    --font-sans: "${typography.fontSans}", ui-sans-serif, system-ui, sans-serif;
    --font-mono: "${typography.fontMono}", ui-monospace, monospace;
    --font-size-base: ${typography.baseSizePx}px;

    /* Radius */
    --radius: ${radius.base / 16}rem;
  }

  .dark {
    --background: 224 71.4% 4.1%;
    --foreground: 210 20% 98%;
    --muted: 215 27.9% 16.9%;
    --border: 215 27.9% 16.9%;
  }
}

/* Tailwind utility bridge */
*, *::before, *::after {
  border-color: hsl(var(--border));
}

body {
  background-color: hsl(var(--background));
  color: hsl(var(--foreground));
  font-family: var(--font-sans);
  font-size: var(--font-size-base);
}
`;
}

function generateTailwindExtend(colors: ColorToken[], radius: RadiusToken): string {
  const colorObj = colors
    .map((c) => `      ${c.key}: "hsl(var(--${c.key}))"`)
    .join(",\n");

  return `// Add this to your tailwind.config.ts → theme.extend:
extend: {
  colors: {
${colorObj},
  },
  borderRadius: {
    lg: "var(--radius)",
    md: "calc(var(--radius) - 2px)",
    sm: "calc(var(--radius) - 4px)",
  },
  fontFamily: {
    sans: ["var(--font-sans)"],
    mono: ["var(--font-mono)"],
  },
},`;
}

// Parse existing tokens.css from project files
function parseExistingTokens(files: ProjectFile[]): Partial<{ colors: ColorToken[]; typography: TypographyToken; radius: RadiusToken }> {
  const tokenFile = files.find((f) => f.path === "src/styles/tokens.css" || f.path === "styles/tokens.css" || f.path === "tokens.css");
  if (!tokenFile?.content) return {};

  const content = tokenFile.content;
  const colors: ColorToken[] = DEFAULT_COLORS.map((dc) => {
    const match = content.match(new RegExp(`--${dc.key}:\\s*(\\d+)\\s+(\\d+)%\\s+(\\d+)%`));
    if (match) {
      const h = parseInt(match[1]), s = parseInt(match[2]), l = parseInt(match[3]);
      // Convert HSL back to hex (approximate)
      const hex = hslToHex(h, s, l);
      return { ...dc, value: hex };
    }
    return dc;
  });

  const fontSansMatch = content.match(/--font-sans:\s*"([^"]+)"/);
  const fontMonoMatch = content.match(/--font-mono:\s*"([^"]+)"/);
  const fontSizeMatch = content.match(/--font-size-base:\s*(\d+)px/);
  const radiusMatch = content.match(/--radius:\s*([\d.]+)rem/);

  return {
    colors,
    typography: {
      fontSans: fontSansMatch?.[1] ?? "Inter",
      fontMono: fontMonoMatch?.[1] ?? "Geist Mono",
      baseSizePx: fontSizeMatch ? parseInt(fontSizeMatch[1]) : 16,
    },
    radius: { base: radiusMatch ? Math.round(parseFloat(radiusMatch[1]) * 16) : 8 },
  };
}

function hslToHex(h: number, s: number, l: number): string {
  s /= 100; l /= 100;
  const a = s * Math.min(l, 1 - l);
  const f = (n: number) => {
    const k = (n + h / 30) % 12;
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * color).toString(16).padStart(2, "0");
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

export function DesignSystemPanel({ projectId, files, onFilesUpdate }: DesignSystemPanelProps) {
  const { toast } = useToast();

  const parsed = parseExistingTokens(files);
  const [colors, setColors] = useState<ColorToken[]>(parsed.colors ?? DEFAULT_COLORS);
  const [typography, setTypography] = useState<TypographyToken>(
    parsed.typography ?? { fontSans: "Inter", fontMono: "Geist Mono", baseSizePx: 16 }
  );
  const [radius, setRadius] = useState<RadiusToken>(parsed.radius ?? { base: 8 });
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [activeTab, setActiveTab] = useState("colors");

  const applyTokens = useCallback(async () => {
    setSaving(true);
    const cssContent = generateCSSFile(colors, typography, radius);

    try {
      const res = await fetch(`/api/projects/${projectId}/design-system`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ cssContent }),
      });

      if (!res.ok) throw new Error(await res.text());

      const { file } = await res.json();
      onFilesUpdate([file]);
      setSaved(true);
      setTimeout(() => setSaved(false), 2500);
      toast({ title: "Design system applied!", description: "tokens.css has been written to your project." });
    } catch (err) {
      toast({ title: "Failed to apply", description: String(err), variant: "destructive" });
    } finally {
      setSaving(false);
    }
  }, [colors, typography, radius, projectId, onFilesUpdate, toast]);

  const resetToDefaults = () => {
    setColors(DEFAULT_COLORS);
    setTypography({ fontSans: "Inter", fontMono: "Geist Mono", baseSizePx: 16 });
    setRadius({ base: 8 });
  };

  const updateColor = (key: string, value: string) => {
    setColors((prev) => prev.map((c) => (c.key === key ? { ...c, value } : c)));
  };

  const cssSnippet = generateTailwindExtend(colors, radius);

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border shrink-0">
        <div className="flex items-center gap-2">
          <Palette className="w-4 h-4 text-primary" />
          <span className="text-sm font-semibold">Design System</span>
        </div>
        <div className="flex items-center gap-1.5">
          <Button variant="ghost" size="sm" onClick={resetToDefaults} className="h-7 px-2 text-xs gap-1">
            <RefreshCw className="w-3 h-3" />
            Reset
          </Button>
          <Button size="sm" onClick={applyTokens} disabled={saving} className="h-7 px-3 text-xs gap-1.5">
            {saving ? <Loader2 className="w-3 h-3 animate-spin" /> : saved ? <Check className="w-3 h-3" /> : <Sparkles className="w-3 h-3" />}
            {saved ? "Applied!" : "Apply"}
          </Button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex-1 overflow-y-auto">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="h-full flex flex-col">
          <TabsList className="w-full rounded-none border-b border-border bg-transparent h-9 px-2 shrink-0 justify-start gap-0">
            <TabsTrigger value="colors" className="h-8 text-xs px-3 rounded-none data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:shadow-none">
              <Palette className="w-3 h-3 mr-1.5" />Colors
            </TabsTrigger>
            <TabsTrigger value="typography" className="h-8 text-xs px-3 rounded-none data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:shadow-none">
              <Type className="w-3 h-3 mr-1.5" />Typography
            </TabsTrigger>
            <TabsTrigger value="spacing" className="h-8 text-xs px-3 rounded-none data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:shadow-none">
              <Sliders className="w-3 h-3 mr-1.5" />Spacing
            </TabsTrigger>
            <TabsTrigger value="export" className="h-8 text-xs px-3 rounded-none data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:shadow-none">
              <Download className="w-3 h-3 mr-1.5" />Export
            </TabsTrigger>
          </TabsList>

          {/* ── Colors ── */}
          <TabsContent value="colors" className="flex-1 overflow-y-auto mt-0 p-4 space-y-5">
            {/* Live color preview strip */}
            <div className="flex rounded-lg overflow-hidden h-8 border border-border">
              {colors.map((c) => (
                <div
                  key={c.key}
                  className="flex-1"
                  style={{ backgroundColor: c.value }}
                  title={c.label}
                />
              ))}
            </div>

            {/* Color tokens */}
            <div className="space-y-3">
              {colors.map((token) => (
                <div key={token.key} className="flex items-center gap-3">
                  {/* Color picker */}
                  <label className="relative cursor-pointer shrink-0">
                    <div
                      className="w-8 h-8 rounded-md border border-border shadow-sm"
                      style={{ backgroundColor: token.value }}
                    />
                    <input
                      type="color"
                      value={token.value}
                      onChange={(e) => updateColor(token.key, e.target.value)}
                      className="absolute inset-0 opacity-0 w-full h-full cursor-pointer"
                    />
                  </label>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-medium text-foreground">{token.label}</span>
                      <input
                        type="text"
                        value={token.value}
                        onChange={(e) => {
                          if (/^#[0-9a-fA-F]{0,6}$/.test(e.target.value)) updateColor(token.key, e.target.value);
                        }}
                        className="text-xs font-mono text-muted-foreground bg-transparent border-0 outline-none w-20 text-right"
                        spellCheck={false}
                      />
                    </div>
                    <p className="text-[10px] text-muted-foreground mt-0.5">{token.description}</p>
                  </div>
                </div>
              ))}
            </div>

            {/* Preset palettes */}
            <div>
              <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wide mb-2">Presets</p>
              <div className="grid grid-cols-4 gap-2">
                {[
                  { name: "Violet", primary: "#7c3aed", accent: "#f59e0b" },
                  { name: "Blue",   primary: "#2563eb", accent: "#06b6d4" },
                  { name: "Rose",   primary: "#e11d48", accent: "#f97316" },
                  { name: "Teal",   primary: "#0d9488", accent: "#8b5cf6" },
                  { name: "Amber",  primary: "#d97706", accent: "#10b981" },
                  { name: "Slate",  primary: "#475569", accent: "#3b82f6" },
                  { name: "Pink",   primary: "#db2777", accent: "#6366f1" },
                  { name: "Green",  primary: "#16a34a", accent: "#f59e0b" },
                ].map((preset) => (
                  <button
                    key={preset.name}
                    onClick={() => {
                      updateColor("primary", preset.primary);
                      updateColor("accent", preset.accent);
                    }}
                    className="flex flex-col items-center gap-1 p-1.5 rounded-md hover:bg-accent/10 transition-colors"
                    title={preset.name}
                  >
                    <div className="flex gap-0.5">
                      <div className="w-4 h-4 rounded-sm" style={{ backgroundColor: preset.primary }} />
                      <div className="w-4 h-4 rounded-sm" style={{ backgroundColor: preset.accent }} />
                    </div>
                    <span className="text-[9px] text-muted-foreground">{preset.name}</span>
                  </button>
                ))}
              </div>
            </div>
          </TabsContent>

          {/* ── Typography ── */}
          <TabsContent value="typography" className="flex-1 overflow-y-auto mt-0 p-4 space-y-5">
            {/* Font preview */}
            <div className="rounded-lg border border-border p-4 bg-muted/30">
              <p className="text-xs text-muted-foreground mb-2">Preview</p>
              <p style={{ fontFamily: `"${typography.fontSans}", sans-serif`, fontSize: `${typography.baseSizePx}px` }}
                 className="font-medium text-foreground leading-snug">
                The quick brown fox jumps over the lazy dog
              </p>
              <p style={{ fontFamily: `"${typography.fontMono}", monospace`, fontSize: `${typography.baseSizePx - 2}px` }}
                 className="text-muted-foreground mt-1">
                {"const hello = 'world';"}
              </p>
            </div>

            <div className="space-y-4">
              {/* Sans font */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium">Sans-serif font</label>
                <select
                  value={typography.fontSans}
                  onChange={(e) => setTypography((t) => ({ ...t, fontSans: e.target.value }))}
                  className="w-full h-8 text-xs rounded-md border border-border bg-background px-2 outline-none"
                >
                  {FONT_OPTIONS.map((f) => <option key={f} value={f}>{f}</option>)}
                </select>
              </div>

              {/* Mono font */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium">Monospace font</label>
                <select
                  value={typography.fontMono}
                  onChange={(e) => setTypography((t) => ({ ...t, fontMono: e.target.value }))}
                  className="w-full h-8 text-xs rounded-md border border-border bg-background px-2 outline-none"
                >
                  {MONO_OPTIONS.map((f) => <option key={f} value={f}>{f}</option>)}
                </select>
              </div>

              {/* Base size */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-medium">Base font size</label>
                  <span className="text-xs font-mono text-muted-foreground">{typography.baseSizePx}px</span>
                </div>
                <input
                  type="range"
                  min={12}
                  max={20}
                  step={1}
                  value={typography.baseSizePx}
                  onChange={(e) => setTypography((t) => ({ ...t, baseSizePx: parseInt(e.target.value) }))}
                  className="w-full accent-primary"
                />
                <div className="flex justify-between text-[10px] text-muted-foreground">
                  <span>12px</span><span>16px</span><span>20px</span>
                </div>
              </div>
            </div>

            {/* Type scale preview */}
            <div>
              <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wide mb-2">Type scale</p>
              <div className="space-y-2 rounded-lg border border-border p-3 bg-muted/20">
                {[
                  { label: "xs",   size: Math.round(typography.baseSizePx * 0.75) },
                  { label: "sm",   size: Math.round(typography.baseSizePx * 0.875) },
                  { label: "base", size: typography.baseSizePx },
                  { label: "lg",   size: Math.round(typography.baseSizePx * 1.125) },
                  { label: "xl",   size: Math.round(typography.baseSizePx * 1.25) },
                  { label: "2xl",  size: Math.round(typography.baseSizePx * 1.5) },
                ].map((s) => (
                  <div key={s.label} className="flex items-baseline gap-2">
                    <span className="text-[10px] text-muted-foreground w-8 shrink-0">{s.label}</span>
                    <span style={{ fontSize: s.size, fontFamily: `"${typography.fontSans}", sans-serif` }}
                          className="text-foreground leading-none">Aa</span>
                    <span className="text-[10px] text-muted-foreground">{s.size}px</span>
                  </div>
                ))}
              </div>
            </div>
          </TabsContent>

          {/* ── Spacing & Radius ── */}
          <TabsContent value="spacing" className="flex-1 overflow-y-auto mt-0 p-4 space-y-5">
            {/* Border radius */}
            <div className="space-y-3">
              <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wide">Border radius</p>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-medium">Base radius</label>
                  <span className="text-xs font-mono text-muted-foreground">{radius.base}px</span>
                </div>
                <input
                  type="range"
                  min={0}
                  max={24}
                  step={2}
                  value={radius.base}
                  onChange={(e) => setRadius({ base: parseInt(e.target.value) })}
                  className="w-full accent-primary"
                />
                <div className="flex justify-between text-[10px] text-muted-foreground">
                  <span>Sharp</span><span>Rounded</span><span>Pill</span>
                </div>
              </div>

              {/* Visual radius preview */}
              <div className="flex gap-3 items-end">
                {[
                  { label: "sm", val: Math.max(0, radius.base - 4) },
                  { label: "md", val: Math.max(0, radius.base - 2) },
                  { label: "lg", val: radius.base },
                  { label: "xl", val: radius.base + 4 },
                ].map((r) => (
                  <div key={r.label} className="flex flex-col items-center gap-1.5">
                    <div
                      className="w-12 h-12 bg-primary/20 border-2 border-primary/40"
                      style={{ borderRadius: r.val }}
                    />
                    <span className="text-[10px] text-muted-foreground">{r.label}</span>
                    <span className="text-[10px] font-mono text-muted-foreground">{r.val}px</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Spacing scale */}
            <div className="space-y-3">
              <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wide">Spacing scale</p>
              <div className="space-y-1.5">
                {[
                  { label: "1", px: 4 },
                  { label: "2", px: 8 },
                  { label: "3", px: 12 },
                  { label: "4", px: 16 },
                  { label: "6", px: 24 },
                  { label: "8", px: 32 },
                  { label: "12", px: 48 },
                  { label: "16", px: 64 },
                ].map((s) => (
                  <div key={s.label} className="flex items-center gap-2">
                    <span className="text-[10px] text-muted-foreground w-6 shrink-0">{s.label}</span>
                    <div className="h-2 bg-primary/30 rounded" style={{ width: s.px * 1.5 }} />
                    <span className="text-[10px] text-muted-foreground">{s.px}px</span>
                  </div>
                ))}
              </div>
              <p className="text-[10px] text-muted-foreground">Tailwind default spacing scale (4px base unit)</p>
            </div>
          </TabsContent>

          {/* ── Export ── */}
          <TabsContent value="export" className="flex-1 overflow-y-auto mt-0 p-4 space-y-4">
            <div>
              <p className="text-xs font-medium mb-1.5">Generated CSS (tokens.css)</p>
              <pre className="text-[10px] font-mono bg-muted/50 rounded-md p-3 overflow-x-auto whitespace-pre-wrap text-muted-foreground leading-relaxed border border-border">
                {generateCSSFile(colors, typography, radius)}
              </pre>
            </div>

            <div>
              <p className="text-xs font-medium mb-1.5">tailwind.config.ts snippet</p>
              <pre className="text-[10px] font-mono bg-muted/50 rounded-md p-3 overflow-x-auto whitespace-pre-wrap text-muted-foreground leading-relaxed border border-border">
                {cssSnippet}
              </pre>
            </div>

            <Button
              variant="outline"
              size="sm"
              className="w-full h-8 text-xs gap-2"
              onClick={() => {
                const blob = new Blob([generateCSSFile(colors, typography, radius)], { type: "text/css" });
                const a = document.createElement("a");
                a.href = URL.createObjectURL(blob);
                a.download = "tokens.css";
                a.click();
              }}
            >
              <Download className="w-3.5 h-3.5" />
              Download tokens.css
            </Button>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
