
import { History,Sparkles,Undo2 } from "lucide-react";
import { getOpenRouterModelLabel } from "@/lib/ai/openrouter-models";
import { LOVABLE_QUICK_EMOJI } from "./types";

interface SkillBadge {
  id: string;
  name: string;
  reason?: string;
}

interface LovableMessageMetaBadgesProps {
  model?: string | null;
  skills?: SkillBadge[];
  credits?: number | null;
  genSeconds?: number | null;
  tokensUsed?: number | null;
  afterSnapshotId?: string | null;
  isCurrentVersion?: boolean;
  onRevertVersion?: () => void;
  onPreviewVersion?: () => void;
  onSaveAsSkill?: () => void;
  reactions?: Set<string>;
  onToggleReaction?: (emoji: string) => void;
}

export function LovableMessageMetaBadges({
  model,
  skills,
  credits,
  genSeconds,
  tokensUsed,
  afterSnapshotId,
  isCurrentVersion,
  onRevertVersion,
  onPreviewVersion,
  onSaveAsSkill,
  reactions,
  onToggleReaction,
}: LovableMessageMetaBadgesProps) {
  const hasSnapshot = !!afterSnapshotId || isCurrentVersion;

  return (
    <>
      {model && (
        <span
          className="text-[10px] text-muted-foreground/40 px-1.5 py-0.5 rounded border border-border/30 select-none font-mono"
          title={`Generated by ${model}`}
        >
          {getOpenRouterModelLabel(model)}
        </span>
      )}
      {skills?.map((s) => (
        <span
          key={s.id}
          className="text-[10px] px-1.5 py-0.5 rounded-full border border-violet-500/30 bg-violet-500/10 text-violet-700 dark:text-violet-300 select-none"
          title={s.reason ? `Auto-attached skill — ${s.reason}` : "Auto-attached skill"}
        >
          ⚡ {s.name}
        </span>
      ))}
      {credits != null && (
        <span
          className="text-[10px] text-muted-foreground/50 px-1.5 py-0.5 rounded border border-border/30 select-none"
          title="Credits used for this message"
        >
          {credits} credit{credits === 1 ? "" : "s"}
        </span>
      )}
      {genSeconds != null && (
        <span className="text-[10px] text-muted-foreground/40 px-0.5 select-none" title="AI generation time">
          ⚡ {genSeconds}s
        </span>
      )}
      {tokensUsed != null && tokensUsed > 0 && (
        <span
          className="text-[10px] text-muted-foreground/35 px-1 select-none font-mono"
          title={`${tokensUsed.toLocaleString()} tokens used`}
        >
          {tokensUsed >= 1000 ? `${(tokensUsed / 1000).toFixed(1)}k tok` : `${tokensUsed} tok`}
        </span>
      )}
      {hasSnapshot && (
        <>
          <button
            onClick={() => {
              if (!isCurrentVersion && afterSnapshotId) onRevertVersion?.();
            }}
            aria-disabled={isCurrentVersion}
            className={`p-1 rounded transition-colors ${
              isCurrentVersion ? "opacity-40 cursor-default" : "hover:bg-white/10"
            }`}
            title={isCurrentVersion ? "This is the current version" : "Revert to this version"}
          >
            <Undo2
              className={`w-3.5 h-3.5 text-muted-foreground ${isCurrentVersion ? "" : "hover:text-foreground"}`}
            />
          </button>
          <button
            onClick={() => {
              if (!isCurrentVersion && afterSnapshotId) onPreviewVersion?.();
            }}
            aria-disabled={isCurrentVersion}
            className={`p-1 rounded transition-colors ${
              isCurrentVersion ? "opacity-40 cursor-default" : "hover:bg-white/10"
            }`}
            title={isCurrentVersion ? "This is the current version" : "Preview this version"}
          >
            <History
              className={`w-3.5 h-3.5 text-muted-foreground ${isCurrentVersion ? "" : "hover:text-foreground"}`}
            />
          </button>
        </>
      )}
      {onSaveAsSkill && (
        <button
          onClick={onSaveAsSkill}
          className="p-1 rounded hover:bg-white/10 transition-colors"
          title="Save as a reusable skill"
        >
          <Sparkles className="w-3.5 h-3.5 text-muted-foreground hover:text-violet-400 transition-colors" />
        </button>
      )}
      {onToggleReaction && (
        <div className="flex items-center gap-0.5 ml-1 opacity-0 group-hover:opacity-100 transition-opacity">
          {LOVABLE_QUICK_EMOJI.map((emoji) => (
            <button
              key={emoji}
              onClick={() => onToggleReaction(emoji)}
              className={`text-[13px] px-0.5 rounded transition-all hover:scale-125 ${
                reactions?.has(emoji) ? "opacity-100" : "opacity-40 hover:opacity-100"
              }`}
              title={`React with ${emoji}`}
            >
              {emoji}
            </button>
          ))}
        </div>
      )}
    </>
  );
}
