/**
 * App-as-MCP code generation — Lovable's architecture, without their SDK.
 *
 * WHY THIS REPLACES THE OLD MODEL
 * ------------------------------
 * The previous implementation (routes/api/apps/$id/mcp.ts) was a
 * PLATFORM-HOSTED PROXY: config rows in `app_mcp`, one static bearer token, and
 * every tool call proxied as an HTTP request to the app's deployed URL. Three
 * consequences fell out of that:
 *
 *   1. Every MCP caller was the SAME principal. A tool could not act "as" the
 *      signed-in end user, so anything user-scoped was impossible and anything
 *      admin-scoped had to be hand-guarded.
 *   2. All traffic flowed through LifemarkAI, so we were in the data path for
 *      other people's user data.
 *   3. Tools could only do what an HTTP endpoint already exposed.
 *
 * A real Lovable export (`@lovable.dev/mcp-js`) does it the other way round, and
 * it is a better design: tools are ordinary TypeScript in the user's own repo,
 * bundled into a Supabase Edge Function that runs in the USER's project, and the
 * caller's JWT is forwarded into the Supabase client — so **RLS performs the
 * authorisation**. That is how their `list_orders` is genuinely admin-only with
 * zero permission code in the tool body.
 *
 * WHAT WE GENERATE (mirrors the export's layout)
 * ----------------------------------------------
 *   src/lib/mcp/runtime.ts          - tiny local defineTool/defineMcp, NO deps
 *   src/lib/mcp/index.ts            - server metadata + tool registry
 *   src/lib/mcp/tools/<kebab>.ts    - one file per tool, editable by the user
 *   supabase/functions/mcp/index.ts - generated Deno edge function (JSON-RPC)
 *   .lifemark/mcp/manifest.json     - discovery manifest
 *
 * DELIBERATE DIFFERENCE: Lovable's tools `import { defineTool } from
 * "@lovable.dev/mcp-js"`, a package only they publish. We emit an equivalent
 * `runtime.ts` into the app instead, so a generated app has no dependency on
 * anything we control and keeps working if it is exported and self-hosted.
 *
 * OWNERSHIP BANNER: the edge function carries the same convention as the real
 * export — it is regenerated on every publish UNLESS the user deletes the
 * banner line, which hands them ownership of the file.
 */

export const MCP_GENERATED_BANNER =
  "// AUTO-GENERATED by LifemarkAI — do not edit. Regenerated on each publish.";
export const MCP_OWNERSHIP_NOTE =
  "// To take ownership, delete the banner line above; publishes then leave this file alone.";

export interface McpToolSpec {
  /** snake_case MCP tool name, e.g. "list_products". */
  name: string;
  /** Human title, e.g. "List products". */
  title?: string;
  description: string;
  /** Postgres table the tool reads. RLS on this table is the access control. */
  table: string;
  /** Columns to select. Defaults to "*". */
  select?: string;
  /** Columns matched case-insensitively by the optional `search` argument. */
  searchColumns?: string[];
  /** Equality filters exposed as tool arguments, e.g. ["status"]. */
  filters?: string[];
  /** Column used for ordering, newest first. */
  orderBy?: string;
  /** Default row cap when the caller omits `limit`. */
  limitDefault?: number;
  /** Fetch exactly one row by this column instead of a list. */
  byColumn?: string;
  /** Hints surfaced to MCP clients. Read-only unless stated otherwise. */
  readOnly?: boolean;
}

export interface McpServerSpec {
  /** MCP server name, e.g. "sastabazzar-mcp". */
  name: string;
  title: string;
  version?: string;
  /** Guidance shown to the calling model about when to use these tools. */
  instructions?: string;
  /** Supabase project ref — used to build the OAuth issuer URL. */
  projectRef: string;
  tools: McpToolSpec[];
}

export interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

const kebab = (s: string) => s.replace(/_/g, "-").toLowerCase();
const titleFor = (t: McpToolSpec) =>
  t.title ?? t.name.replace(/_/g, " ").replace(/^./, (c) => c.toUpperCase());

/** JSON-Schema for a tool's arguments — used in the manifest and tools/list. */
export function inputSchemaFor(t: McpToolSpec): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  if (t.byColumn) {
    properties[t.byColumn] = {
      type: "string",
      description: `The ${t.byColumn} of the ${t.table} row to fetch.`,
    };
    required.push(t.byColumn);
  } else {
    if (t.searchColumns?.length) {
      properties.search = {
        type: "string",
        description: `Optional case-insensitive text matched against ${t.searchColumns.join(" or ")}.`,
      };
    }
    for (const f of t.filters ?? []) {
      properties[f] = { type: "string", description: `Optional ${f} filter.` };
    }
    properties.limit = {
      type: "integer",
      minimum: 1,
      maximum: 100,
      description: `Maximum rows to return (default ${t.limitDefault ?? 20}).`,
    };
  }

  return { type: "object", properties, ...(required.length ? { required } : {}) };
}

function annotationsFor(t: McpToolSpec) {
  const readOnly = t.readOnly !== false;
  return { readOnlyHint: readOnly, idempotentHint: readOnly, openWorldHint: false };
}

/**
 * The local runtime. Deliberately dependency-free: `defineTool` is an identity
 * function that exists for types and discoverability, exactly as it does in the
 * real export — the shape is the contract, not the implementation.
 */
const RUNTIME_TS = `${MCP_GENERATED_BANNER}
${MCP_OWNERSHIP_NOTE}
//
// Minimal MCP runtime. No external packages: a generated app must keep working
// after export/self-host without depending on the platform that made it.

export interface ToolContext {
  /** True when the request carried a valid bearer token. */
  isAuthenticated(): boolean;
  /** The caller's raw JWT. Forward it to Supabase so RLS applies to THEM. */
  getToken(): string;
}

export interface ToolResult {
  content: Array<{ type: "text"; text: string }>;
  structuredContent?: Record<string, unknown>;
  isError?: boolean;
}

export interface ToolDefinition {
  name: string;
  title: string;
  description: string;
  inputSchema: Record<string, unknown>;
  annotations: {
    readOnlyHint: boolean;
    idempotentHint: boolean;
    openWorldHint: boolean;
  };
  handler: (args: Record<string, any>, ctx: ToolContext) => Promise<ToolResult>;
}

export function defineTool(def: ToolDefinition): ToolDefinition {
  return def;
}

export interface McpDefinition {
  name: string;
  title: string;
  version: string;
  instructions?: string;
  auth: { type: "oauth"; issuer: string; acceptedAudiences: string[] };
  tools: ToolDefinition[];
}

export function defineMcp(def: McpDefinition): McpDefinition {
  return def;
}

export const auth = {
  oauth: {
    issuer(opts: { issuer: string; acceptedAudiences?: string | string[] }) {
      const aud = opts.acceptedAudiences ?? "authenticated";
      return {
        type: "oauth" as const,
        issuer: opts.issuer,
        acceptedAudiences: Array.isArray(aud) ? aud : [aud],
      };
    },
  },
};

/** Convenience result helpers so tool bodies stay short. */
export function ok(data: unknown, key = "data"): ToolResult {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { [key]: data },
  };
}

export function fail(message: string): ToolResult {
  return { content: [{ type: "text", text: message }], isError: true };
}
`;

/** One tool file. Body mirrors the real export's query shape. */
function toolFile(t: McpToolSpec): string {
  const select = t.select ?? "*";
  const limitDefault = t.limitDefault ?? 20;
  const args = t.byColumn
    ? `{ ${t.byColumn} }`
    : `{ ${[t.searchColumns?.length ? "search" : null, ...(t.filters ?? []), "limit"]
        .filter(Boolean)
        .join(", ")} }`;

  const body = t.byColumn
    ? `    const { data, error } = await sb(ctx)
      .from(${JSON.stringify(t.table)})
      .select(${JSON.stringify(select)})
      .eq(${JSON.stringify(t.byColumn)}, ${t.byColumn})
      .maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Not found");
    return ok(data, ${JSON.stringify(t.table)});`
    : `    let q = sb(ctx)
      .from(${JSON.stringify(t.table)})
      .select(${JSON.stringify(select)})${
        t.orderBy
          ? `\n      .order(${JSON.stringify(t.orderBy)}, { ascending: false })`
          : ""
      }
      .limit(limit ?? ${limitDefault});
${
  // Emit a real template literal, as the reference export does. The \` and \${
  // below are escaped for THIS template, so the generated file contains a plain
  // `q.or(\`name.ilike.%${search}%,...\`)` rather than a string + .replace().
  t.searchColumns?.length
    ? `    if (search) q = q.or(\`${t.searchColumns
        .map((c) => `${c}.ilike.%\${search}%`)
        .join(",")}\`);\n`
    : ""
}${(t.filters ?? [])
        .map((f) => `    if (${f}) q = q.eq(${JSON.stringify(f)}, ${f});\n`)
        .join("")}    const { data, error } = await q;
    if (error) return fail(error.message);
    return ok(data, ${JSON.stringify(t.table)});`;

  return `${MCP_GENERATED_BANNER}
${MCP_OWNERSHIP_NOTE}
import { createClient } from "@supabase/supabase-js";
import { defineTool, ok, fail, type ToolContext } from "../runtime";

// The caller's own JWT is forwarded, so Row Level Security decides what this
// tool can see. Do NOT swap in the service-role key — that would bypass RLS and
// expose every row to every caller.
function sb(ctx: ToolContext) {
  return createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_PUBLISHABLE_KEY!,
    {
      global: { headers: { Authorization: \`Bearer \${ctx.getToken()}\` } },
      auth: { persistSession: false, autoRefreshToken: false },
    },
  );
}

export default defineTool({
  name: ${JSON.stringify(t.name)},
  title: ${JSON.stringify(titleFor(t))},
  description: ${JSON.stringify(t.description)},
  inputSchema: ${JSON.stringify(inputSchemaFor(t), null, 2).replace(/\n/g, "\n  ")},
  annotations: ${JSON.stringify(annotationsFor(t))},
  handler: async (${args}, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
${body}
  },
});
`;
}

function indexFile(spec: McpServerSpec): string {
  const imports = spec.tools
    .map((t) => `import ${camel(t.name)} from "./tools/${kebab(t.name)}";`)
    .join("\n");
  return `${MCP_GENERATED_BANNER}
${MCP_OWNERSHIP_NOTE}
import { auth, defineMcp } from "./runtime";
${imports}

const projectRef = import.meta.env.VITE_SUPABASE_PROJECT_ID ?? "project-ref-unset";

export default defineMcp({
  name: ${JSON.stringify(spec.name)},
  title: ${JSON.stringify(spec.title)},
  version: ${JSON.stringify(spec.version ?? "0.1.0")},
${spec.instructions ? `  instructions: ${JSON.stringify(spec.instructions)},\n` : ""}  auth: auth.oauth.issuer({
    issuer: \`https://\${projectRef}.supabase.co/auth/v1\`,
    acceptedAudiences: "authenticated",
  }),
  tools: [${spec.tools.map((t) => camel(t.name)).join(", ")}],
});
`;
}

const camel = (s: string) => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());

/**
 * The Supabase Edge Function. Self-contained Deno + JSON-RPC 2.0 over a single
 * POST, which is the MCP streamable-HTTP transport.
 *
 * Auth model, matching the real export: the function does not mint or hold a
 * token. It reads the caller's bearer, hands it to supabase-js, and lets RLS
 * decide. An unauthenticated call still gets a well-formed MCP error rather than
 * a crash, so clients can negotiate.
 */
function edgeFunction(spec: McpServerSpec): string {
  const toolDefs = spec.tools.map((t) => ({
    name: t.name,
    title: titleFor(t),
    description: t.description,
    inputSchema: inputSchemaFor(t),
    annotations: annotationsFor(t),
    table: t.table,
    select: t.select ?? "*",
    searchColumns: t.searchColumns ?? [],
    filters: t.filters ?? [],
    orderBy: t.orderBy ?? null,
    limitDefault: t.limitDefault ?? 20,
    byColumn: t.byColumn ?? null,
  }));

  return `${MCP_GENERATED_BANNER}
${MCP_OWNERSHIP_NOTE}
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by LifemarkAI.
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";

const SERVER = ${JSON.stringify(
    {
      name: spec.name,
      title: spec.title,
      version: spec.version ?? "0.1.0",
    },
    null,
    2,
  )};

const INSTRUCTIONS = ${JSON.stringify(spec.instructions ?? "")};
const TOOLS = ${JSON.stringify(toolDefs, null, 2)};

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, "Content-Type": "application/json" },
  });

const rpcOk = (id: unknown, result: unknown) => json({ jsonrpc: "2.0", id, result });
const rpcErr = (id: unknown, code: number, message: string) =>
  json({ jsonrpc: "2.0", id, error: { code, message } });

/** Caller-scoped client: RLS applies to the CALLER, never to a service role. */
function sb(token: string) {
  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY")!,
    {
      global: { headers: { Authorization: \`Bearer \${token}\` } },
      auth: { persistSession: false, autoRefreshToken: false },
    },
  );
}

async function runTool(def: any, args: Record<string, any>, token: string) {
  const client = sb(token);
  if (def.byColumn) {
    const { data, error } = await client
      .from(def.table)
      .select(def.select)
      .eq(def.byColumn, args[def.byColumn])
      .maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { [def.table]: data },
    };
  }
  let q = client.from(def.table).select(def.select).limit(Number(args.limit) || def.limitDefault);
  if (def.orderBy) q = q.order(def.orderBy, { ascending: false });
  if (args.search && def.searchColumns.length) {
    q = q.or(def.searchColumns.map((c: string) => \`\${c}.ilike.%\${args.search}%\`).join(","));
  }
  for (const f of def.filters) if (args[f] != null) q = q.eq(f, args[f]);
  const { data, error } = await q;
  if (error) return { content: [{ type: "text", text: error.message }], isError: true };
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { [def.table]: data },
  };
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  let body: any;
  try {
    body = await req.json();
  } catch {
    return rpcErr(null, -32700, "Parse error");
  }

  const { id, method, params } = body ?? {};
  const token = (req.headers.get("authorization") ?? "").replace(/^Bearer /i, "");

  if (method === "initialize") {
    return rpcOk(id, {
      protocolVersion: "2024-11-05",
      capabilities: { tools: {} },
      serverInfo: SERVER,
      ...(INSTRUCTIONS ? { instructions: INSTRUCTIONS } : {}),
    });
  }

  if (method === "ping") return rpcOk(id, {});

  if (method === "tools/list") {
    return rpcOk(id, {
      tools: TOOLS.map((t: any) => ({
        name: t.name,
        title: t.title,
        description: t.description,
        inputSchema: t.inputSchema,
        annotations: t.annotations,
      })),
    });
  }

  if (method === "tools/call") {
    const def = TOOLS.find((t: any) => t.name === params?.name);
    if (!def) return rpcErr(id, -32602, \`Unknown tool: \${params?.name}\`);
    if (!token) {
      return rpcOk(id, {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true,
      });
    }
    try {
      return rpcOk(id, await runTool(def, params?.arguments ?? {}, token));
    } catch (err) {
      return rpcOk(id, {
        content: [{ type: "text", text: (err as Error).message }],
        isError: true,
      });
    }
  }

  return rpcErr(id, -32601, \`Method not found: \${method}\`);
});
`;
}

function manifest(spec: McpServerSpec): string {
  return JSON.stringify(
    {
      version: 1,
      generator: "lifemarkai",
      path: "/functions/v1/mcp",
      auth: {
        type: "oauth",
        issuer: `https://${spec.projectRef}.supabase.co/auth/v1`,
        accepted_audiences: ["authenticated"],
      },
      mcp: {
        server: {
          name: spec.name,
          version: spec.version ?? "0.1.0",
          title: spec.title,
        },
        tools: spec.tools.map((t) => ({
          name: t.name,
          title: titleFor(t),
          description: t.description,
          annotations: annotationsFor(t),
          inputSchema: inputSchemaFor(t),
        })),
      },
    },
    null,
    2,
  );
}

/**
 * Full generated file set for a project's MCP server.
 *
 * `existing` lets callers preserve user-owned files: any path whose current
 * content no longer starts with the generated banner is skipped, matching the
 * export's "delete the banner to take ownership" convention.
 */
export function generateAppMcpFiles(
  spec: McpServerSpec,
  existing: Array<{ path: string; content?: string | null }> = [],
): GeneratedFile[] {
  const owned = new Set(
    existing
      .filter((f) => f.content != null && !f.content.startsWith(MCP_GENERATED_BANNER))
      .map((f) => f.path),
  );

  const files: GeneratedFile[] = [
    { path: "src/lib/mcp/runtime.ts", content: RUNTIME_TS, language: "typescript" },
    { path: "src/lib/mcp/index.ts", content: indexFile(spec), language: "typescript" },
    ...spec.tools.map((t) => ({
      path: `src/lib/mcp/tools/${kebab(t.name)}.ts`,
      content: toolFile(t),
      language: "typescript",
    })),
    {
      path: "supabase/functions/mcp/index.ts",
      content: edgeFunction(spec),
      language: "typescript",
    },
    { path: ".lifemark/mcp/manifest.json", content: manifest(spec), language: "json" },
  ];

  return files.filter((f) => !owned.has(f.path));
}
