const ts=require('typescript'),fs=require('fs');
const src=fs.readFileSync('src/components/editor/chat-panel.tsx','utf8');
const re=/const SCAFFOLD_FILE_RE =\s*([\s\S]*?);\n/.exec(src)[1];
const fn=/function countUserAuthoredFiles\([\s\S]*?\n\}/.exec(src)[0];
const js=ts.transpileModule(`${'const SCAFFOLD_FILE_RE = '+re};\nconst GROWN_HOME_PAGE_CHARS = 1500;\n${fn}\nmodule.exports={countUserAuthoredFiles};`,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const M=new (require('module'))('x'); M._compile(js,'x.js');
const c=M.exports.countUserAuthoredFiles;
let pass=0,fail=0;const t=(n,cond,d='')=>{cond?(pass++,console.log('  PASS',n)):(fail++,console.log('  FAIL',n,d))};
const F=(p,len=0)=>({path:p,content:'x'.repeat(len)});
const SCAFFOLD=['index.html','package.json','vite.config.ts','components.json','tsconfig.json','tsconfig.app.json','tsconfig.node.json','tailwind.config.ts','postcss.config.js','.gitignore','README.md','public/robots.txt','src/App.css','src/App.tsx','src/main.tsx','src/index.css','src/vite-env.d.ts','src/lib/utils.ts','src/hooks/use-mobile.tsx','src/pages/Index.tsx','src/pages/NotFound.tsx','src/components/ui/sonner.tsx','src/components/ui/tooltip.tsx','src/components/layout/Header.tsx','src/components/layout/Footer.tsx'].map(p=>F(p,432));
t('fresh 25-file scaffold => 0 (routes to BUILD)', c(SCAFFOLD)===0, c(SCAFFOLD));
const TSS=['package.json','tsconfig.json','vite.config.ts','tailwind.config.js','postcss.config.js','src/styles.css','src/router.tsx','src/routes/__root.tsx','src/routes/index.tsx','src/lib/utils.ts','src/components/layout/Header.tsx','src/components/layout/Footer.tsx'].map(p=>F(p,432));
t('fresh TanStack scaffold => 0', c(TSS)===0, c(TSS));
const BUILT=[...SCAFFOLD,F('src/components/Hero.tsx',900),F('src/components/Pricing.tsx',900),F('src/data/classes.ts',400)];
t('built app => >0 (routes to AGENT)', c(BUILT)===3, c(BUILT));
const INLINE=[...SCAFFOLD.filter(f=>f.path!=='src/pages/Index.tsx'),F('src/pages/Index.tsx',9000)];
t('app living only in a grown Index.tsx => >0', c(INLINE)===1, c(INLINE));
t('empty project => 0', c([])===0);
t('windows backslashes normalised', c([F('src\\pages\\Index.tsx',432)])===0);
console.log(`\n=== ${pass} passed, ${fail} failed ===`);process.exit(fail?1:0);
