-- Migration 056: Telegram account linking
--
-- Lets a LifemarkAI user connect their Telegram account so they can trigger
-- builds via the @LifemarkAIBot from a phone. Two columns on profiles:
--
--   • telegram_chat_id     — once the user runs `/start <token>` in Telegram,
--                            the bot writes the chat ID here. Unique so one
--                            Telegram account ≠ multiple LifemarkAI users.
--   • telegram_link_token  — one-time short-lived token generated by the
--                            dashboard's "Connect Telegram" button. Cleared
--                            after consumption.

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS telegram_chat_id    BIGINT,
  ADD COLUMN IF NOT EXISTS telegram_link_token TEXT,
  ADD COLUMN IF NOT EXISTS telegram_linked_at  TIMESTAMPTZ;

-- One Telegram chat ID maps to one LifemarkAI user; partial index so the
-- common NULL case isn't indexed.
CREATE UNIQUE INDEX IF NOT EXISTS profiles_telegram_chat_id_unique
  ON profiles (telegram_chat_id)
  WHERE telegram_chat_id IS NOT NULL;

-- Fast lookups on token redemption.
CREATE UNIQUE INDEX IF NOT EXISTS profiles_telegram_link_token_unique
  ON profiles (telegram_link_token)
  WHERE telegram_link_token IS NOT NULL;

COMMENT ON COLUMN profiles.telegram_chat_id IS
  'Chat ID of the user''s Telegram account. NULL until /start <token> runs.';
COMMENT ON COLUMN profiles.telegram_link_token IS
  'One-time token issued by the dashboard. Consumed by the bot on /start.';
