/**
 * TanStack Start scaffold — the STRICT app structure LifemarkAI generates
 * (Lovable parity: TanStack Start + SSR is Lovable's default for new apps).
 *
 * Canonical layout (see tanstack.com/start build-from-scratch):
 *   src/routes/__root.tsx   — root document (html/head/body, HeadContent, Scripts)
 *   src/routes/index.tsx    — home route (createFileRoute + optional createServerFn)
 *   src/router.tsx          — getRouter() → createRouter(routeTree)
 *   src/routeTree.gen.ts    — AUTO-GENERATED by the tanstackStart Vite plugin
 *   src/styles.css          — Tailwind entry (imported into __root via ?url)
 *   src/lib/utils.ts        — cn() for shadcn/ui
 *   vite.config.ts          — tanstackStart() + viteReact() (react AFTER start)
 *   tsconfig.json           — jsx react-jsx, Bundler resolution, @/* → src/*
 *
 * The Start Vite plugin owns the entry — NO index.html and NO src/main.tsx.
 */

import { BASE_APP_DEPENDENCIES, BASE_APP_DEV_DEPENDENCIES } from "@/lib/preview/base-app-deps";

export interface ScaffoldFile {
  path: string;
  content: string;
  language: string;
}

/** TanStack Start dependency set — the shadcn ecosystem minus react-router-dom
 *  (TanStack Router replaces it), plus Start + Router. */
export const TANSTACK_START_DEPENDENCIES: Record<string, string> = (() => {
  const deps = { ...BASE_APP_DEPENDENCIES };
  delete deps["react-router-dom"]; // routing is TanStack Router in Start apps
  return {
    ...deps,
    "@tanstack/react-start": "^1.168.0",
    "@tanstack/react-router": "^1.170.0",
  };
})();

export const TANSTACK_START_DEV_DEPENDENCIES: Record<string, string> = {
  ...BASE_APP_DEV_DEPENDENCIES,
  "@types/node": "^20.14.0",
};

const PACKAGE_JSON = (extra: Record<string, string> = {}): string =>
  JSON.stringify(
    {
      name: "lifemarkai-app",
      version: "0.0.1",
      private: true,
      type: "module",
      scripts: { dev: "vite dev", build: "vite build", start: "node .output/server/index.mjs" },
      dependencies: { ...TANSTACK_START_DEPENDENCIES, ...extra },
      devDependencies: { ...TANSTACK_START_DEV_DEPENDENCIES },
    },
    null,
    2,
  );

const VITE_CONFIG = `import { defineConfig } from "vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";

export default defineConfig({
  // host + allowedHosts so the preview works behind the sandbox tunnel.
  server: { host: true, allowedHosts: true, port: 3000 },
  resolve: {
    alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) },
  },
  plugins: [
    tanstackStart(),
    // react's Vite plugin MUST come after TanStack Start's plugin.
    viteReact(),
  ],
});
`;

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      jsx: "react-jsx",
      moduleResolution: "Bundler",
      module: "ESNext",
      target: "ES2022",
      lib: ["ES2022", "DOM", "DOM.Iterable"],
      skipLibCheck: true,
      strictNullChecks: true,
      strict: true,
      noEmit: true,
      baseUrl: ".",
      paths: { "@/*": ["./src/*"] },
      types: ["node"],
    },
    include: ["src", "vite.config.ts"],
  },
  null,
  2,
);

const TAILWIND_CONFIG = `import tailwindcssAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [tailwindcssAnimate],
};
`;

const POSTCSS_CONFIG = `export default { plugins: { tailwindcss: {}, autoprefixer: {} } };
`;

const STYLES_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

* { box-sizing: border-box; }
`;

const ROUTER_TSX = `import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// The TanStack Start Vite plugin calls getRouter() to build the app router.
export function getRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: "intent",
  });
}
`;

const ROOT_TSX = `import type { ReactNode } from "react";
import {
  Outlet,
  createRootRoute,
  HeadContent,
  Scripts,
} from "@tanstack/react-router";
import appCss from "../styles.css?url";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "LifemarkAI App" },
    ],
    links: [{ rel: "stylesheet", href: appCss }],
  }),
  component: RootComponent,
});

function RootComponent() {
  return (
    <RootDocument>
      <Outlet />
    </RootDocument>
  );
}

function RootDocument({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}
`;

const INDEX_TSX = `import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  component: Home,
});

function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-neutral-950 text-neutral-100">
      <div className="text-center space-y-3">
        <h1 className="text-4xl font-bold tracking-tight">Welcome</h1>
        <p className="text-neutral-400">
          Your TanStack Start app is ready. Edit{" "}
          <code className="rounded bg-neutral-800 px-1.5 py-0.5 text-sm">src/routes/index.tsx</code>{" "}
          to begin.
        </p>
      </div>
    </main>
  );
}
`;

const UTILS_TS = `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/** shadcn/ui class-name helper. */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;

/**
 * Return the full TanStack Start scaffold. `pkgExtra` merges into dependencies
 * (parity with the Vite-React scaffold helper).
 */
export function tanstackStartScaffold(pkgExtra: Record<string, string> = {}): ScaffoldFile[] {
  return [
    { path: "package.json", language: "json", content: PACKAGE_JSON(pkgExtra) },
    { path: "tsconfig.json", language: "json", content: TSCONFIG },
    { path: "vite.config.ts", language: "typescript", content: VITE_CONFIG },
    { path: "tailwind.config.js", language: "javascript", content: TAILWIND_CONFIG },
    { path: "postcss.config.js", language: "javascript", content: POSTCSS_CONFIG },
    { path: "src/styles.css", language: "css", content: STYLES_CSS },
    { path: "src/router.tsx", language: "typescriptreact", content: ROUTER_TSX },
    { path: "src/routes/__root.tsx", language: "typescriptreact", content: ROOT_TSX },
    { path: "src/routes/index.tsx", language: "typescriptreact", content: INDEX_TSX },
    { path: "src/lib/utils.ts", language: "typescript", content: UTILS_TS },
  ];
}

/** True if a file set is a TanStack Start project (used by preview patchers). */
export function isTanStackStartProject(files: Array<{ path: string; content?: string | null }>): boolean {
  return files.some((f) => {
    const p = f.path.replace(/\\/g, "/");
    if (p === "package.json" && f.content) return /@tanstack\/react-start/.test(f.content);
    if (/vite\.config\.(t|j)sx?$/.test(p) && f.content) return /tanstackStart\s*\(/.test(f.content);
    return false;
  });
}
